version: '3.9'

services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#    networks:
#      - default

  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: libraryms_db
    ports:
      - "5432:5432"
    networks:
      - default

networks:
  default: